version: "3.5"

services:
  api01: &api
    build: .
    hostname: api1
    network_mode: host
    environment:
      PORT: 3000
      DB: "sqlite:app/db/db.sqlite"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api2
    environment:
      PORT: 3001
      DB: "sqlite:app/db/db.sqlite"

  db:
    image: alpine:latest
    volumes:
      - db:/data
    command: sh -c "apk --no-cache add sqlite && sqlite3 /data/db.sqlite < /data/init.sql"

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"
volumes:
  db:


